<script>

function handleError(errFunc, errMsg) {
    console.log("[" + errFunc + "] :", errMsg);
}

</script>